# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: 'grrdrdntr/Rep4ADO'
    FodConnection: 'KyraTest'
    ReleaseOptions: '2'
    ApplicationName: 'UAT 24.2'
    BusinessCriticality: '1'
    ApplicationType: '2'
    ReleaseName: 'ADO'
    Owner: 97077
    EntitlementSelection: '0'
    Entitlement: 12631
    EntitlementPreference: '1'
    OverrideScanSettings: '1'
    AssessmentTypeId: '271'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'none'
    PolicyFailAction: '0'
- task: FortifyDASTAutomated@2
  inputs:
    FodConnection: 'KyraTest'
    ReleaseOptions: '0'
    ReleaseId: 170611
    AssessmentTypeId: 149
    EntitlementId: 3556
    EntitlementFrequencyType: 'Subscription'
    OverrideScanSettings: '2'
    PolicyFailAction: '0'